### ISSUE TITLE
Simplify generics

### ISSUE THREAD

**Issue by marksands** [IanKeen/Defaultable#1]
Any reason why you can't piggy back off of the `Default.ValueType` and drop the `T`?  I went through the exercise of converting your playground over and it seemed to work.

Makes the following much more palatable! 😛 

```
struct Model: Codable, Hashable {
    @Defaultable<True> var bool: Bool
    @Defaultable<Zero<Float>> var float: Float
    @Defaultable<FortyTwo<Int>> var int: Int
    @Defaultable<EmptyString> var string: String
}
```

**Comment by IanKeen** [comment]
I've simplified this a fair bit into a gist: https://gist.github.com/IanKeen/e5db10e66d617e5fe89135a9f125cc39
